/**
 * Static voice data: locale names, available voice presets, language defaults,
 * and language-code maps for each fallback engine.
 */

export const LOCALE_TO_LANGUAGE_NAME: Record<string, string> = {
    'en-US': 'English (United States)',
    'en-GB': 'English (United Kingdom)',
    'en-AU': 'English (Australia)',
    'en-CA': 'English (Canada)',
    'en-IN': 'English (India)',
    'en-IE': 'English (Ireland)',
    'en-NZ': 'English (New Zealand)',
    'en-PH': 'English (Philippines)',
    'en-ZA': 'English (South Africa)',
    'ta-IN': 'Tamil (India)',
    'ta-LK': 'Tamil (Sri Lanka)',
    'hi-IN': 'Hindi (India)',
    'te-IN': 'Telugu (India)',
    'kn-IN': 'Kannada (India)',
    'ml-IN': 'Malayalam (India)',
    'gu-IN': 'Gujarati (India)',
    'mr-IN': 'Marathi (India)',
    'bn-IN': 'Bengali (India)',
    'pa-IN': 'Punjabi (India)',
    'ur-IN': 'Urdu (India)',
    'ar-XA': 'Arabic (General)',
    'ar-AE': 'Arabic (United Arab Emirates)',
    'ar-BH': 'Arabic (Bahrain)',
    'ar-DZ': 'Arabic (Algeria)',
    'ar-EG': 'Arabic (Egypt)',
    'ar-IQ': 'Arabic (Iraq)',
    'ar-JO': 'Arabic (Jordan)',
    'ar-KW': 'Arabic (Kuwait)',
    'ar-LB': 'Arabic (Lebanon)',
    'ar-LY': 'Arabic (Libya)',
    'ar-MA': 'Arabic (Morocco)',
    'ar-OM': 'Arabic (Oman)',
    'ar-PS': 'Arabic (Palestine)',
    'ar-QA': 'Arabic (Qatar)',
    'ar-SA': 'Arabic (Saudi Arabia)',
    'ar-SY': 'Arabic (Syria)',
    'ar-TN': 'Arabic (Tunisia)',
    'ar-YE': 'Arabic (Yemen)',
    'bg-BG': 'Bulgarian (Bulgaria)',
    'ca-ES': 'Catalan (Spain)',
    'cs-CZ': 'Czech (Czech Republic)',
    'cy-GB': 'Welsh (United Kingdom)',
    'da-DK': 'Danish (Denmark)',
    'de-DE': 'German (Germany)',
    'de-AT': 'German (Austria)',
    'de-CH': 'German (Switzerland)',
    'el-GR': 'Greek (Greece)',
    'es-ES': 'Spanish (Spain)',
    'es-MX': 'Spanish (Mexico)',
    'es-AR': 'Spanish (Argentina)',
    'es-BO': 'Spanish (Bolivia)',
    'es-CL': 'Spanish (Chile)',
    'es-CO': 'Spanish (Colombia)',
    'es-CR': 'Spanish (Costa Rica)',
    'es-CU': 'Spanish (Cuba)',
    'es-DO': 'Spanish (Dominican Republic)',
    'es-EC': 'Spanish (Ecuador)',
    'es-GQ': 'Spanish (Equatorial Guinea)',
    'es-GT': 'Spanish (Guatemala)',
    'es-HN': 'Spanish (Honduras)',
    'es-NI': 'Spanish (Nicaragua)',
    'es-PA': 'Spanish (Panama)',
    'es-PE': 'Spanish (Peru)',
    'es-PR': 'Spanish (Puerto Rico)',
    'es-PY': 'Spanish (Paraguay)',
    'es-SV': 'Spanish (El Salvador)',
    'es-US': 'Spanish (United States)',
    'es-UY': 'Spanish (Uruguay)',
    'es-VE': 'Spanish (Venezuela)',
    'et-EE': 'Estonian (Estonia)',
    'fi-FI': 'Finnish (Finland)',
    'fil-PH': 'Filipino (Philippines)',
    'fr-FR': 'French (France)',
    'fr-BE': 'French (Belgium)',
    'fr-CA': 'French (Canada)',
    'fr-CH': 'French (Switzerland)',
    'ga-IE': 'Irish (Ireland)',
    'gl-ES': 'Galician (Spain)',
    'he-IL': 'Hebrew (Israel)',
    'hr-HR': 'Croatian (Croatia)',
    'hu-HU': 'Hungarian (Hungary)',
    'id-ID': 'Indonesian (Indonesia)',
    'is-IS': 'Icelandic (Iceland)',
    'it-IT': 'Italian (Italy)',
    'ja-JP': 'Japanese (Japan)',
    'jv-ID': 'Javanese (Indonesia)',
    'ka-GE': 'Georgian (Georgia)',
    'kk-KZ': 'Kazakh (Kazakhstan)',
    'km-KH': 'Khmer (Cambodia)',
    'ko-KR': 'Korean (South Korea)',
    'lo-LA': 'Lao (Laos)',
    'lt-LT': 'Lithuanian (Lithuania)',
    'lv-LV': 'Latvian (Latvia)',
    'mk-MK': 'Macedonian (North Macedonia)',
    'mn-MN': 'Mongolian (Mongolia)',
    'ms-MY': 'Malay (Malaysia)',
    'mt-MT': 'Maltese (Malta)',
    'my-MM': 'Burmese (Myanmar)',
    'nb-NO': 'Norwegian Bokmål (Norway)',
    'ne-NP': 'Nepali (Nepal)',
    'nl-NL': 'Dutch (Netherlands)',
    'nl-BE': 'Dutch (Belgium)',
    'pl-PL': 'Polish (Poland)',
    'pt-BR': 'Portuguese (Brazil)',
    'pt-PT': 'Portuguese (Portugal)',
    'ro-RO': 'Romanian (Romania)',
    'ru-RU': 'Russian (Russia)',
    'si-LK': 'Sinhala (Sri Lanka)',
    'sk-SK': 'Slovak (Slovakia)',
    'sl-SI': 'Slovenian (Slovenia)',
    'sq-AL': 'Albanian (Albania)',
    'sr-RS': 'Serbian (Serbia)',
    'sv-SE': 'Swedish (Sweden)',
    'sw-KE': 'Swahili (Kenya)',
    'sw-TZ': 'Swahili (Tanzania)',
    'th-TH': 'Thai (Thailand)',
    'tr-TR': 'Turkish (Turkey)',
    'uk-UA': 'Ukrainian (Ukraine)',
    'uz-UZ': 'Uzbek (Uzbekistan)',
    'vi-VN': 'Vietnamese (Vietnam)',
    'zh-CN': 'Chinese (Mainland)',
    'zh-HK': 'Chinese (Hong Kong)',
    'zh-TW': 'Chinese (Taiwan)',
};

/** Featured voice presets grouped by language key and gender */
export const AVAILABLE_VOICES: Record<string, { male: string[]; female: string[] }> = {
    english: {
        male: ['en-US-GuyNeural', 'en-US-ChristopherNeural', 'en-GB-RyanNeural', 'en-IN-PrabhatNeural', 'en-US-BrianNeural', 'en-AU-WilliamNeural'],
        female: ['en-US-JennyNeural', 'en-US-AriaNeural', 'en-US-SaraNeural', 'en-GB-SoniaNeural', 'en-US-MichelleNeural', 'en-AU-NatashaNeural'],
    },
    tamil: {
        male: ['ta-IN-ValluvarNeural'],
        female: ['ta-IN-PallaviNeural'],
    },
    hindi: {
        male: ['hi-IN-MadhurNeural'],
        female: ['hi-IN-SwaraNeural'],
    },
    spanish: {
        male: ['es-ES-AlvaroNeural', 'es-MX-JorgeNeural'],
        female: ['es-ES-ElviraNeural', 'es-MX-DaliaNeural'],
    },
    french: {
        male: ['fr-FR-HenriNeural', 'fr-CA-AntoineNeural'],
        female: ['fr-FR-DeniseNeural', 'fr-CA-SylvieNeural'],
    },
    german: {
        male: ['de-DE-ConradNeural', 'de-AT-JonasNeural'],
        female: ['de-DE-KatjaNeural', 'de-AT-IngridNeural'],
    },
    telugu: {
        male: ['te-IN-MohanNeural'],
        female: ['te-IN-ShrutiNeural'],
    },
    malayalam: {
        male: ['ml-IN-MidhunNeural'],
        female: ['ml-IN-SobhanaNeural'],
    },
    kannada: {
        male: ['kn-IN-GaganNeural'],
        female: ['kn-IN-SapnaNeural'],
    },
    italian: {
        male: ['it-IT-DiegoNeural', 'it-IT-BeniaminoNeural'],
        female: ['it-IT-ElsaNeural', 'it-IT-IsabellaNeural'],
    },
    japanese: {
        male: ['ja-JP-KeitaNeural', 'ja-JP-DaichiNeural'],
        female: ['ja-JP-NanamiNeural', 'ja-JP-AoiNeural'],
    },
    korean: {
        male: ['ko-KR-InJoonNeural'],
        female: ['ko-KR-SunHiNeural'],
    },
    portuguese: {
        male: ['pt-BR-AntonioNeural', 'pt-PT-DuarteNeural'],
        female: ['pt-BR-FranciscaNeural', 'pt-PT-RaquelNeural'],
    },
    russian: {
        male: ['ru-RU-DmitryNeural'],
        female: ['ru-RU-SvetlanaNeural'],
    },
    arabic: {
        male: ['ar-SA-HamedNeural', 'ar-EG-ShakirNeural'],
        female: ['ar-SA-ZariyahNeural', 'ar-EG-SalmaNeural'],
    },
    chinese: {
        male: ['zh-CN-YunxiNeural', 'zh-CN-YunyangNeural'],
        female: ['zh-CN-XiaoxiaoNeural', 'zh-CN-XiaoyiNeural'],
    },
    bengali: {
        male: ['bn-IN-BashkarNeural'],
        female: ['bn-IN-TanishaaNeural'],
    },
    gujarati: {
        male: ['gu-IN-NiranjanNeural'],
        female: ['gu-IN-DhwaniNeural'],
    },
    marathi: {
        male: ['mr-IN-ManoharNeural'],
        female: ['mr-IN-AarohiNeural'],
    },
    punjabi: {
        male: ['pa-IN-ByomNeural'],
        female: ['pa-IN-CharleenNeural'],
    },
    urdu: {
        male: ['ur-IN-SalmanNeural'],
        female: ['ur-IN-GulNeural'],
    },
};

/** Default voice per language key */
export const LANGUAGE_DEFAULTS: Record<string, string> = {
    tamil: 'ta-IN-PallaviNeural',
    hindi: 'hi-IN-SwaraNeural',
    spanish: 'es-ES-ElviraNeural',
    french: 'fr-FR-DeniseNeural',
    german: 'de-DE-KatjaNeural',
    english: 'en-US-JennyNeural',
    italian: 'it-IT-ElsaNeural',
    japanese: 'ja-JP-NanamiNeural',
    korean: 'ko-KR-SunHiNeural',
    portuguese: 'pt-BR-FranciscaNeural',
    russian: 'ru-RU-SvetlanaNeural',
    arabic: 'ar-SA-ZariyahNeural',
    chinese: 'zh-CN-XiaoxiaoNeural',
    bengali: 'bn-IN-TanishaaNeural',
    gujarati: 'gu-IN-DhwaniNeural',
    marathi: 'mr-IN-AarohiNeural',
    punjabi: 'pa-IN-CharleenNeural',
    urdu: 'ur-IN-GulNeural',
};

/** Language key → Windows SAPI culture tag */
export const WINDOWS_SAPI_LANGUAGE_MAP: Record<string, string> = {
    arabic: 'ar-SA',
    chinese: 'zh-CN',
    english: 'en-US',
    french: 'fr-FR',
    german: 'de-DE',
    hindi: 'hi-IN',
    italian: 'it-IT',
    japanese: 'ja-JP',
    korean: 'ko-KR',
    portuguese: 'pt-BR',
    russian: 'ru-RU',
    spanish: 'es-ES',
    tamil: 'ta-IN',
};
