import fs from 'fs-extra';
import path from 'path';
import { DownloadResult, HistoryEntry, MetadataRecord } from '../models/video';
import { AppConfig } from '../config';

/**
 * Writes (or merges into) metadata.json in the download directory,
 * containing structured records for every successfully downloaded video.
 */
export async function writeMetadataJson(
  config: AppConfig,
  results: DownloadResult[],
): Promise<string> {
  const metadataPath = path.join(config.downloadDir, 'metadata.json');
  await fs.ensureDir(config.downloadDir);

  let existing: MetadataRecord[] = [];
  if (await fs.pathExists(metadataPath)) {
    try {
      existing = await fs.readJson(metadataPath);
      if (!Array.isArray(existing)) existing = [];
    } catch {
      existing = [];
    }
  }

  const newRecords: MetadataRecord[] = results
    .filter((r) => r.success && r.localPath)
    .map((r) => ({
      title: r.video.title,
      creator: r.video.creator,
      license: r.video.license,
      license_url: r.video.licenseUrl,
      provider: r.video.provider,
      download_url: r.video.downloadUrl,
      local_path: r.localPath as string,
      file_size_bytes: r.bytesDownloaded,
      downloaded_at: new Date().toISOString(),
    }));

  const combined = [...existing, ...newRecords];
  await fs.writeJson(metadataPath, combined, { spaces: 2 });
  return metadataPath;
}

/**
 * Writes (or appends to) a human-readable ATTRIBUTION.txt file, which
 * users can include with redistributed content to satisfy CC/attribution
 * license terms.
 */
export async function writeAttributionFile(
  config: AppConfig,
  results: DownloadResult[],
): Promise<string> {
  const attributionPath = path.join(config.downloadDir, 'ATTRIBUTION.txt');
  await fs.ensureDir(config.downloadDir);

  const successful = results.filter((r) => r.success);
  if (successful.length === 0) return attributionPath;

  const blocks = successful.map((r) => {
    const v = r.video;
    return [
      v.title,
      `Creator: ${v.creator}`,
      `License: ${v.license}`,
      `License URL: ${v.licenseUrl || 'N/A'}`,
      `Provider: ${v.provider}`,
      `Source: ${v.sourcePageUrl}`,
      '',
    ].join('\n');
  });

  const header = `Attribution information generated by free-video-downloader on ${new Date().toISOString()}\n${'='.repeat(70)}\n\n`;
  const existingContent = (await fs.pathExists(attributionPath))
    ? await fs.readFile(attributionPath, 'utf-8')
    : '';

  const newContent = existingContent + (existingContent ? '\n' : header) + blocks.join('\n');
  await fs.writeFile(attributionPath, existingContent ? newContent : header + blocks.join('\n'));

  return attributionPath;
}

/** Appends entries to the persistent download history file. */
export async function appendHistory(config: AppConfig, results: DownloadResult[]): Promise<void> {
  let history: HistoryEntry[] = [];
  if (await fs.pathExists(config.historyFile)) {
    try {
      history = await fs.readJson(config.historyFile);
      if (!Array.isArray(history)) history = [];
    } catch {
      history = [];
    }
  }

  const timestamp = new Date().toISOString();
  const entries: HistoryEntry[] = results.map((r) => ({
    keyword: '',
    timestamp,
    provider: r.video.provider,
    title: r.video.title,
    localPath: r.localPath ?? '',
    success: r.success,
  }));

  const combined = [...history, ...entries];
  await fs.ensureDir(path.dirname(config.historyFile));
  await fs.writeJson(config.historyFile, combined, { spaces: 2 });
}

/** Reads the full download history, or an empty array if none exists. */
export async function readHistory(config: AppConfig): Promise<HistoryEntry[]> {
  if (!(await fs.pathExists(config.historyFile))) return [];
  try {
    const data = await fs.readJson(config.historyFile);
    return Array.isArray(data) ? data : [];
  } catch {
    return [];
  }
}

/** Exports metadata.json content to a CSV file. */
export async function exportMetadataToCsv(config: AppConfig): Promise<string | null> {
  const metadataPath = path.join(config.downloadDir, 'metadata.json');
  if (!(await fs.pathExists(metadataPath))) return null;

  const records: MetadataRecord[] = await fs.readJson(metadataPath);
  if (records.length === 0) return null;

  const headers = Object.keys(records[0]) as Array<keyof MetadataRecord>;
  const escapeCsv = (value: string | number): string => {
    const str = String(value);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const lines = [
    headers.join(','),
    ...records.map((r) => headers.map((h) => escapeCsv(r[h])).join(',')),
  ];

  const csvPath = path.join(config.downloadDir, 'metadata.csv');
  await fs.writeFile(csvPath, lines.join('\n'));
  return csvPath;
}